### ISSUE TITLE
Errror on Repository

### ISSUE THREAD

**Issue by mikysal78** [us2h/k8s-ansible#1]
Hi,
i try your playbook but i have error on repository.
I check url and i have error 404

https://github.com/us2h/k8s-ansible/blob/fd08b8afba7a65e49e3fbcdc118231e390d4590b/roles/kubernetes/tasks/repositories.yml#L23

Howto fix?
Best regards,
Michele

**Comment by mikysal78** [comment]
i try with

#Kubernetes
```
---
- block:  # Add Kubernetes APT repository

  - name: Ensure /etc/apt/keyrings exists
    file:
      path: /etc/apt/keyrings
      state: directory
      mode: '0755'

  - name: Add public key 
    get_url:
      url: https://pkgs.k8s.io/core:/stable:/v1.28/deb/Release.key
      dest: /etc/apt/keyrings/kubernetes-apt-keyring.asc


  - name: Add Kubernetes apt repository
    apt_repository:
      repo: 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.asc] https://pkgs.k8s.io/core:/stable:/v1.28/deb/ /'
      state: present
      filename: kubernetes.list
      update_cache: yes

  when:
    - ansible_os_family == 'Debian'
 ```
 
 #Docker
 ```
---
- block:  # Add Docker APT repository

  - name: Add Docker GPG key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      id: 0EBFCD88
      state: present

  - name: Add public key 
    get_url:
      url: https://download.docker.com/linux/debian/gpg
      dest: /etc/apt/keyrings/docker.asc


  - name: Add Docker APT repository
    apt_repository:
      repo: "deb [arch={{ ansible_architecture | replace('x86_64', 'amd64') | replace('aarch64', 'arm64') }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
      state: present
      update_cache: yes

  when:
    - ansible_os_family == 'Debian'
 ```
